package game

const (
	MSG_NULL_IOTA = uint16(iota)
	MSG_PING_REQUEST
	MSG_PING_RESPONSE
	MSG_WELCOME
	MSG_SPECIAL_1
	MSG_SPECIAL_2
	MSG_ROOM_COUNT_REQUEST
	MSG_ROOM_COUNT_RESPONSE
	MSG_ROOM_UPDATE_NAME = 1000
	MSG_ROOM_UPDATE_STATUS
)
